services:
  - type: web
    name: lab-slot-booking-system
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NPM_CONFIG_UNSAFE_PERM
        value: "true"
      - key: PYTHON
        value: python3